repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: uv run --locked ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: Ruff format
        entry: uv run --locked ruff format
        language: system
        types_or: [python, pyi]

  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.58.0
    hooks:
      - id: oxfmt
        args: [--no-error-on-unmatched-pattern]
        types_or: [text]
        files: \.(md|json|jsonc|ya?ml|toml)$
        exclude: ^\.github/workflows/
