"""Shared danger detector test configuration."""

from aerial_danger.location_presets import LOCATION_PRESETS
from aerial_danger.pattern_utils import resolve_locality_patterns

REGION_PATTERNS = [
    r"\bки(ї|є)в(а|у|ом|е|і)?\b",
    r"\bкиївщин(а|и|і|у|ою)?\b",
    r"\bстолиц(і|ю|я)?\b",
    r"\bсумщин(а|і|у|ою)?\b",
    r"\bхарківщин\w*\b",
    r"\bчернігівщин\w*\b",
    r"\bзапорізьк\w* област\w*\b",
    r"\bодещин\w*\b",
    r"\bдонеччин\w*\b",
    r"\bмиколаївщин\w*\b",
    r"\bчеркащин\w*\b",
    r"\bдніпропетровщин(а|и|і|у|ою)?\b",
    r"\bхерсон(а|у|ом|і)?\b",
    r"\bбц\b",
    r"\bбрянськ\w*\b",
    r"\bчорноморськ\w*\b",
    r"(до|на) нас",
    r"наш(у|ої) област(ьі|і)?",
]

LOCALITY_PATTERNS = resolve_locality_patterns(
    [],
    list(LOCATION_PRESETS),
    [
        "chernihiv_oblast_semenivka",
        "dnipropetrovsk_oblast_kryvyi_rih",
        "donetsk_oblast_sloviansk",
        "kharkiv_oblast_kharkiv",
        "kharkiv_oblast_kozacha_lopan",
        "kharkiv_oblast_kupiansk",
        "kharkiv_oblast_vokzal",
        "kherson_oblast_kherson",
        "kyiv_akademmistechko",
        "kyiv_antonov",
        "kyiv_beresteiska",
        "kyiv_berkovets",
        "kyiv_bilychi",
        "kyiv_chokolivka",
        "kyiv_halahany",
        "kyiv_nyvky",
        "kyiv_oblast_bila_tserkva",
        "kyiv_oblast_bilohorodka",
        "kyiv_oblast_brovary",
        "kyiv_obolon",
        "kyiv_shuliavka",
        "kyiv_solomianka",
        "kyiv_sviatoshyn",
        "kyiv_syrets",
        "kyiv_tovarnyi",
        "kyiv_troieshchyna",
        "kyiv_vynohradar",
        "kyiv_zhuliany",
        "mykolaiv_oblast_mykolaiv",
        "mykolaiv_oblast_ochakiv",
        "odesa_oblast_karolino_buhaz",
        "odesa_oblast_novi_biliari",
        "odesa_oblast_ovidiopol",
        "sumy_oblast_myropillia",
        "sumy_oblast_shostka",
        "sumy_oblast_shostkynskyi_raion",
        "sumy_oblast_sumy",
        "sumy_oblast_varachyne",
        "zaporizhzhia_oblast_zaporizhzhia",
    ],
)
